/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.4.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the MentalModelTrigger type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MentalModelTrigger{}

// MentalModelTrigger Trigger settings for a mental model.
type MentalModelTrigger struct {
	// If true, refresh this mental model after observations consolidation (real-time mode)
	RefreshAfterConsolidation *bool `json:"refresh_after_consolidation,omitempty"`
}

// NewMentalModelTrigger instantiates a new MentalModelTrigger object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMentalModelTrigger() *MentalModelTrigger {
	this := MentalModelTrigger{}
	var refreshAfterConsolidation bool = false
	this.RefreshAfterConsolidation = &refreshAfterConsolidation
	return &this
}

// NewMentalModelTriggerWithDefaults instantiates a new MentalModelTrigger object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMentalModelTriggerWithDefaults() *MentalModelTrigger {
	this := MentalModelTrigger{}
	var refreshAfterConsolidation bool = false
	this.RefreshAfterConsolidation = &refreshAfterConsolidation
	return &this
}

// GetRefreshAfterConsolidation returns the RefreshAfterConsolidation field value if set, zero value otherwise.
func (o *MentalModelTrigger) GetRefreshAfterConsolidation() bool {
	if o == nil || IsNil(o.RefreshAfterConsolidation) {
		var ret bool
		return ret
	}
	return *o.RefreshAfterConsolidation
}

// GetRefreshAfterConsolidationOk returns a tuple with the RefreshAfterConsolidation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MentalModelTrigger) GetRefreshAfterConsolidationOk() (*bool, bool) {
	if o == nil || IsNil(o.RefreshAfterConsolidation) {
		return nil, false
	}
	return o.RefreshAfterConsolidation, true
}

// HasRefreshAfterConsolidation returns a boolean if a field has been set.
func (o *MentalModelTrigger) HasRefreshAfterConsolidation() bool {
	if o != nil && !IsNil(o.RefreshAfterConsolidation) {
		return true
	}

	return false
}

// SetRefreshAfterConsolidation gets a reference to the given bool and assigns it to the RefreshAfterConsolidation field.
func (o *MentalModelTrigger) SetRefreshAfterConsolidation(v bool) {
	o.RefreshAfterConsolidation = &v
}

func (o MentalModelTrigger) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MentalModelTrigger) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RefreshAfterConsolidation) {
		toSerialize["refresh_after_consolidation"] = o.RefreshAfterConsolidation
	}
	return toSerialize, nil
}

type NullableMentalModelTrigger struct {
	value *MentalModelTrigger
	isSet bool
}

func (v NullableMentalModelTrigger) Get() *MentalModelTrigger {
	return v.value
}

func (v *NullableMentalModelTrigger) Set(val *MentalModelTrigger) {
	v.value = val
	v.isSet = true
}

func (v NullableMentalModelTrigger) IsSet() bool {
	return v.isSet
}

func (v *NullableMentalModelTrigger) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMentalModelTrigger(val *MentalModelTrigger) *NullableMentalModelTrigger {
	return &NullableMentalModelTrigger{value: val, isSet: true}
}

func (v NullableMentalModelTrigger) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMentalModelTrigger) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


