/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.4.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TagGroupNot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagGroupNot{}

// TagGroupNot Compound NOT group: child filter must NOT match.
type TagGroupNot struct {
	Not Not `json:"not"`
}

type _TagGroupNot TagGroupNot

// NewTagGroupNot instantiates a new TagGroupNot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagGroupNot(not Not) *TagGroupNot {
	this := TagGroupNot{}
	this.Not = not
	return &this
}

// NewTagGroupNotWithDefaults instantiates a new TagGroupNot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagGroupNotWithDefaults() *TagGroupNot {
	this := TagGroupNot{}
	return &this
}

// GetNot returns the Not field value
func (o *TagGroupNot) GetNot() Not {
	if o == nil {
		var ret Not
		return ret
	}

	return o.Not
}

// GetNotOk returns a tuple with the Not field value
// and a boolean to check if the value has been set.
func (o *TagGroupNot) GetNotOk() (*Not, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Not, true
}

// SetNot sets field value
func (o *TagGroupNot) SetNot(v Not) {
	o.Not = v
}

func (o TagGroupNot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagGroupNot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["not"] = o.Not
	return toSerialize, nil
}

func (o *TagGroupNot) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"not",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagGroupNot := _TagGroupNot{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTagGroupNot)

	if err != nil {
		return err
	}

	*o = TagGroupNot(varTagGroupNot)

	return err
}

type NullableTagGroupNot struct {
	value *TagGroupNot
	isSet bool
}

func (v NullableTagGroupNot) Get() *TagGroupNot {
	return v.value
}

func (v *NullableTagGroupNot) Set(val *TagGroupNot) {
	v.value = val
	v.isSet = true
}

func (v NullableTagGroupNot) IsSet() bool {
	return v.isSet
}

func (v *NullableTagGroupNot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagGroupNot(val *TagGroupNot) *NullableTagGroupNot {
	return &NullableTagGroupNot{value: val, isSet: true}
}

func (v NullableTagGroupNot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagGroupNot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


