/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.4.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DocumentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentResponse{}

// DocumentResponse Response model for get document endpoint.
type DocumentResponse struct {
	Id string `json:"id"`
	BankId string `json:"bank_id"`
	OriginalText string `json:"original_text"`
	ContentHash NullableString `json:"content_hash"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	MemoryUnitCount int32 `json:"memory_unit_count"`
	// Tags associated with this document
	Tags []string `json:"tags,omitempty"`
}

type _DocumentResponse DocumentResponse

// NewDocumentResponse instantiates a new DocumentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentResponse(id string, bankId string, originalText string, contentHash NullableString, createdAt string, updatedAt string, memoryUnitCount int32) *DocumentResponse {
	this := DocumentResponse{}
	this.Id = id
	this.BankId = bankId
	this.OriginalText = originalText
	this.ContentHash = contentHash
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.MemoryUnitCount = memoryUnitCount
	return &this
}

// NewDocumentResponseWithDefaults instantiates a new DocumentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentResponseWithDefaults() *DocumentResponse {
	this := DocumentResponse{}
	return &this
}

// GetId returns the Id field value
func (o *DocumentResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DocumentResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DocumentResponse) SetId(v string) {
	o.Id = v
}

// GetBankId returns the BankId field value
func (o *DocumentResponse) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *DocumentResponse) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *DocumentResponse) SetBankId(v string) {
	o.BankId = v
}

// GetOriginalText returns the OriginalText field value
func (o *DocumentResponse) GetOriginalText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OriginalText
}

// GetOriginalTextOk returns a tuple with the OriginalText field value
// and a boolean to check if the value has been set.
func (o *DocumentResponse) GetOriginalTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OriginalText, true
}

// SetOriginalText sets field value
func (o *DocumentResponse) SetOriginalText(v string) {
	o.OriginalText = v
}

// GetContentHash returns the ContentHash field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DocumentResponse) GetContentHash() string {
	if o == nil || o.ContentHash.Get() == nil {
		var ret string
		return ret
	}

	return *o.ContentHash.Get()
}

// GetContentHashOk returns a tuple with the ContentHash field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentResponse) GetContentHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContentHash.Get(), o.ContentHash.IsSet()
}

// SetContentHash sets field value
func (o *DocumentResponse) SetContentHash(v string) {
	o.ContentHash.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *DocumentResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DocumentResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DocumentResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *DocumentResponse) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *DocumentResponse) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *DocumentResponse) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetMemoryUnitCount returns the MemoryUnitCount field value
func (o *DocumentResponse) GetMemoryUnitCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryUnitCount
}

// GetMemoryUnitCountOk returns a tuple with the MemoryUnitCount field value
// and a boolean to check if the value has been set.
func (o *DocumentResponse) GetMemoryUnitCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryUnitCount, true
}

// SetMemoryUnitCount sets field value
func (o *DocumentResponse) SetMemoryUnitCount(v int32) {
	o.MemoryUnitCount = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *DocumentResponse) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentResponse) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *DocumentResponse) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *DocumentResponse) SetTags(v []string) {
	o.Tags = v
}

func (o DocumentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["bank_id"] = o.BankId
	toSerialize["original_text"] = o.OriginalText
	toSerialize["content_hash"] = o.ContentHash.Get()
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["memory_unit_count"] = o.MemoryUnitCount
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

func (o *DocumentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"bank_id",
		"original_text",
		"content_hash",
		"created_at",
		"updated_at",
		"memory_unit_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocumentResponse := _DocumentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocumentResponse)

	if err != nil {
		return err
	}

	*o = DocumentResponse(varDocumentResponse)

	return err
}

type NullableDocumentResponse struct {
	value *DocumentResponse
	isSet bool
}

func (v NullableDocumentResponse) Get() *DocumentResponse {
	return v.value
}

func (v *NullableDocumentResponse) Set(val *DocumentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentResponse(val *DocumentResponse) *NullableDocumentResponse {
	return &NullableDocumentResponse{value: val, isSet: true}
}

func (v NullableDocumentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


