/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.4.18
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)


// Not struct for Not
type Not struct {
	TagGroupAnd *TagGroupAnd
	TagGroupLeaf *TagGroupLeaf
	TagGroupNot *TagGroupNot
	TagGroupOr *TagGroupOr
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *Not) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into TagGroupAnd
	err = json.Unmarshal(data, &dst.TagGroupAnd);
	if err == nil {
		jsonTagGroupAnd, _ := json.Marshal(dst.TagGroupAnd)
		if string(jsonTagGroupAnd) == "{}" { // empty struct
			dst.TagGroupAnd = nil
		} else {
			return nil // data stored in dst.TagGroupAnd, return on the first match
		}
	} else {
		dst.TagGroupAnd = nil
	}

	// try to unmarshal JSON data into TagGroupLeaf
	err = json.Unmarshal(data, &dst.TagGroupLeaf);
	if err == nil {
		jsonTagGroupLeaf, _ := json.Marshal(dst.TagGroupLeaf)
		if string(jsonTagGroupLeaf) == "{}" { // empty struct
			dst.TagGroupLeaf = nil
		} else {
			return nil // data stored in dst.TagGroupLeaf, return on the first match
		}
	} else {
		dst.TagGroupLeaf = nil
	}

	// try to unmarshal JSON data into TagGroupNot
	err = json.Unmarshal(data, &dst.TagGroupNot);
	if err == nil {
		jsonTagGroupNot, _ := json.Marshal(dst.TagGroupNot)
		if string(jsonTagGroupNot) == "{}" { // empty struct
			dst.TagGroupNot = nil
		} else {
			return nil // data stored in dst.TagGroupNot, return on the first match
		}
	} else {
		dst.TagGroupNot = nil
	}

	// try to unmarshal JSON data into TagGroupOr
	err = json.Unmarshal(data, &dst.TagGroupOr);
	if err == nil {
		jsonTagGroupOr, _ := json.Marshal(dst.TagGroupOr)
		if string(jsonTagGroupOr) == "{}" { // empty struct
			dst.TagGroupOr = nil
		} else {
			return nil // data stored in dst.TagGroupOr, return on the first match
		}
	} else {
		dst.TagGroupOr = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(Not)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *Not) MarshalJSON() ([]byte, error) {
	if src.TagGroupAnd != nil {
		return json.Marshal(&src.TagGroupAnd)
	}

	if src.TagGroupLeaf != nil {
		return json.Marshal(&src.TagGroupLeaf)
	}

	if src.TagGroupNot != nil {
		return json.Marshal(&src.TagGroupNot)
	}

	if src.TagGroupOr != nil {
		return json.Marshal(&src.TagGroupOr)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableNot struct {
	value *Not
	isSet bool
}

func (v NullableNot) Get() *Not {
	return v.value
}

func (v *NullableNot) Set(val *Not) {
	v.value = val
	v.isSet = true
}

func (v NullableNot) IsSet() bool {
	return v.isSet
}

func (v *NullableNot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNot(val *Not) *NullableNot {
	return &NullableNot{value: val, isSet: true}
}

func (v NullableNot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


